### ISSUE TITLE
How to render multiple objects to one image

### ISSUE THREAD

**Issue by RMTT** [ScrappyCocco/ScrapEngine#38]
I'm a newbie to vulkan, i read your code, but there is so many jump between the functions. The most one i cannot understand is that how to render multiple objects to one image, such as skybox,ball and the light.

**Comment by ScrappyCocco** [comment]
Hello and nice to meet you!

First of all, remember that I'm not an expert in Vulkan, so if you need help or want to learn more, consider joining the [Vulkan Discord Server](https://discordapp.com/invite/tFdvbEj) or [the Vulkan Discord Server](https://app.slack.com/client/TDMDFS87M/CDTJ9BELF).

I suppose you're new to Vulkan and that you did or saw a tutorial that only render a single mesh, so I'll try to explain how to render more than one mesh.

The light rendering is a more advanced topic, that I still don't know well, and you probably want to study how to implement a Forward Rendering or a Deferred Rendering structure.
(Remember that this engine in its current state only render the sun directional light in a Forward Rendering way)

So, first of all, everything that you want the GPU to draw must be in a [Command Buffer](https://vulkan.lunarg.com/doc/view/1.0.26.0/linux/vkspec.chunked/ch05.html).

The Command Buffer (I'll call it CB) contains commands that can be submitted to a Queue (and so to the GPU).

The example you have seen probably has a small CB, that's built only one time and load only one mesh.

This because if you want to add/remove stuff to draw, you must **rebuild** the CB.
This engine, use two command buffers (see [wiki](https://github.com/ScrappyCocco/ScrapEngine/wiki/Tasks-running-in-background)): one is the one currently being drawn, and another is being rebuilt in background, to allow meshes to be added/removed anytime.

It's completely up to you when or how frequently rebuilt the CB, depending of what you need to achieve, because remember that's an heavy operation.
(Note: In fact, you should only render meshes that are on screen, with a tecnique called Occlusion Culling).

So, about my engine: the parts you want to see are probably these:
* [RenderManager.cpp#L457](https://github.com/ScrappyCocco/ScrapEngine/blob/master/ScrapEngine/ScrapEngine/Engine/Rendering/Manager/RenderManager.cpp#L457): this is the function `create_command_buffer()` that rebuild the CB at runtime, it use a variable called `flip_flop` to swap the two CB i mentioned before. The important part for you is that `for` cycle, for every mesh, it submit it to the CB to render it;
* [StandardCommandBuffer.cpp#L219](https://github.com/ScrappyCocco/ScrapEngine/blob/master/ScrapEngine/ScrapEngine/Engine/Rendering/Buffer/CommandBuffer/StandardCommandBuffer/StandardCommandBuffer.cpp#L219): this is the main CB class i use. Remember it also contains commands to draw shadows above the linked function, so the important part for you is the one i sent: to draw a mesh you *(usually)* must call:
  1. `vkCmdBindPipeline(...)` 
  2. `vkCmdBindVertexBuffers(...)` 
  3. `vkCmdBindIndexBuffer(...)` 
  4. `vkCmdBindDescriptorSets(...)` 
  5. `vkCmdDrawIndexed(...)`

Remember that mine is like `command_buffers[i].bindPipeline(...)` because i use the C++ API.

Remember also that you need to call CB functions such as `vkBeginCommandBuffer()` and `vkCmdBeginRenderPass()`.
You can read about submitting a mesh [in this tutorial section](https://vulkan-tutorial.com/Vertex_buffers/Vertex_input_description).

Hope this helped you, please tell me if you have more questions about this.

**Summary of important things:**
* Everything you want to draw must be in a command in a Command Buffer;
* The command buffer must be in the Recording state to submit commands to it, and in the Executable state to be executed.

(See the [Vulkan Doc](https://vulkan.lunarg.com/doc/view/1.0.26.0/linux/vkspec.chunked/ch05.html) page to read more...)

**Comment by RMTT** [comment]
Thanks you reply! There is my understanding about how to render multiple objects from your code:
+ create vertex buffer and index buffer for every obj
+ using one commandbuffer to draw every object at one time
i can find the `command_buffers_[index].command_buffer->end_command_buffer_render_pass();` but cannot find the begin of render pass.

And the gui render, i found you are using `ImGui::Render();`, i'm not familiar with imgui, is this using a specified commandbuffer?

**Comment by ScrappyCocco** [comment]
HHello again!

So, about the main CB:
* It begin here to be in Recording state: [RenderManager.cpp#L437](https://github.com/ScrappyCocco/ScrapEngine/blob/af17d2e43c5e7d8269b6646c2824e4d352f7205b/ScrapEngine/ScrapEngine/Engine/Rendering/Manager/RenderManager.cpp#L437)
* Note that general functions are in the parent class, and most of them are called from `create_command_buffer`, such as: 
  * [begin_command_buffer-BaseCommandBuffer.cpp#L12](https://github.com/ScrappyCocco/ScrapEngine/blob/af17d2e43c5e7d8269b6646c2824e4d352f7205b/ScrapEngine/ScrapEngine/Engine/Rendering/Buffer/CommandBuffer/BaseCommandBuffer.cpp#L12)
  * [close_command_buffer-BaseCommandBuffer.cpp#L27](https://github.com/ScrappyCocco/ScrapEngine/blob/af17d2e43c5e7d8269b6646c2824e4d352f7205b/ScrapEngine/ScrapEngine/Engine/Rendering/Buffer/CommandBuffer/BaseCommandBuffer.cpp#L27)
  * [end_command_buffer_render_pass-BaseCommandBuffer.cpp#L35](https://github.com/ScrappyCocco/ScrapEngine/blob/af17d2e43c5e7d8269b6646c2824e4d352f7205b/ScrapEngine/ScrapEngine/Engine/Rendering/Buffer/CommandBuffer/BaseCommandBuffer.cpp#L35)
* The RenderPass begin in the `init_command_buffer` function: [StandardCommandBuffer.cpp#L159](https://github.com/ScrappyCocco/ScrapEngine/blob/af17d2e43c5e7d8269b6646c2824e4d352f7205b/ScrapEngine/ScrapEngine/Engine/Rendering/Buffer/CommandBuffer/StandardCommandBuffer/StandardCommandBuffer.cpp#L159)

The UI is a bit different, because again, when the UI change the Command Buffer may change. If you want to note how it works, this [Sascha example](https://github.com/SaschaWillems/Vulkan/blob/master/examples/imgui/main.cpp) contains the minimal stuff to draw the UI, and you can see stuff better in there.

That example use a single CB and rebuild it every frame, my engine use a third CD that's rebuilt on background (in a thread) every frame (see [wiki](https://github.com/ScrappyCocco/ScrapEngine/wiki/Tasks-running-in-background#gui-command-buffer)).

The basic concept is this, for every frame:
* Read UI commands that are between `ImGui::NewFrame();` and `ImGui::Render();`, in my engine this are defined by the user, for example [here in the game (MainMenu.cpp)](https://github.com/ScrappyCocco/ScrapEngine/blob/af17d2e43c5e7d8269b6646c2824e4d352f7205b/ScrapEngine/SimpleGame/GameObjects/MainMenu/MainMenu.cpp#L16);
* When the commands are recorded, [generate buffers data](https://github.com/ScrappyCocco/ScrapEngine/blob/af17d2e43c5e7d8269b6646c2824e4d352f7205b/ScrapEngine/ScrapEngine/Engine/Rendering/Gui/VulkanImGui.cpp#L129);
* Add the UI buffers to the CB, in my case [GuiCommandBuffer::load_ui](https://github.com/ScrappyCocco/ScrapEngine/blob/af17d2e43c5e7d8269b6646c2824e4d352f7205b/ScrapEngine/ScrapEngine/Engine/Rendering/Buffer/CommandBuffer/GuiCommandBuffer/GuiCommandBuffer.cpp#L63).

Then, as i said, i use three CB: two for the meshes and one for the GUI, so for one frame i submit **both** the meshes-CB and the UI-CB to the Queue. 

Again, this is totally up to you, you can use a single CB for everything or 100 different CB.

The example i linked above for the UI (that i really suggest you to look at) use a single CB but do exactly the same steps mentioned above here.

Hope this helps you to understand the basics, do not make too many steps at time because it's very confusing, do small things every steps and you will understand better.

**Comment by RMTT** [comment]
Thanks again! i'm creating my own game engine now for understand the vulkan, maybe we can talking on the telegram or icq, because my phone cannot register the Discord : (

**Comment by ScrappyCocco** [comment]
Sorry but i don't provide personal support on Telegram or similar 😅
I suggest you to use Discord on pc downloading it or on Browser, both Discord and Slack runs in any pc browser if you don't want to download them.

**Comment by RMTT** [comment]
all right, but thanks, i will do more learning.By the way, maybe you can provide a cmake version : )

**Comment by ScrappyCocco** [comment]
Good luck then!

I know, sorry, i don't know cmake well enough to move the project to cmake but that's something i could do sooner or later ^^
