### ISSUE TITLE
How to link an external git repo as a library in github.

### ISSUE THREAD

**Issue by lukarolak** [ScrappyCocco/ScrapEngine#41]
https://github.com/ScrappyCocco/ScrapEngine/tree/master/external

Here you have managed to link external repositories to your library folder. I would like to do the same thing too, could you tell me how you did it?

**Comment by ScrappyCocco** [comment]
Hello and nice to meet you!

So, i usually use a GUI for that, GitKraken, but doing it crom CL shouldn't be a lot different
(double-check the commands i tell you if you prefer, just understand the concept).

An external repo is considered as "Submodule". A submodule can point to any commit of the external repo.

**For example**, you can add the submodule GLFW at version 3.3 and keep it there, so anyone who will clone your repository will have GLFW pointing at the same commit as you at version 3.3.

## Submodule file
### First way
First of all you can add a submodule using the file `.gitmodules` you can see mine here: [.gitmodules](https://github.com/ScrappyCocco/ScrapEngine/blob/master/.gitmodules).

That file contains the url to the external repo and the local folder where you keep the submodule. Note that writing manually in the file probably isn't the best way and require you to run:
```
git submodule update --init --recursive
``` 
to "clone" the submodule into the specified folder.

### Other **(better)** way to add a submodule
You can use the command
```
git submodule add https://github.com/ExampleUser/ExampleSubmodule.git externals/ExampleSubmodule/
```
that will do everything for you i think. (You can change the example path of course).

## Submodule commit pointer
Once you downloaded the submodule, you may want to change the commit where it points.

I think you can just use standard git commands **in the submodule folder**, for example:
```
git checkout 3.3
```
to check a specific version, because:
> "Submodule repositories stay in a detached HEAD state pointing to a specific commit. Changing that commit simply involves checking out a different tag or commit then adding the change to the parent repository." (quote from [stackoverflow](https://stackoverflow.com/questions/10914022/how-do-i-check-out-a-specific-version-of-a-submodule-using-git-submodule)).

If you did all correctly you can commit the changes in the **main** repo and check on github if the submodule exist and point to the correct commit. (It will appear as `submodule @ commit` so you can check the commit pointer).

## End
If you have other question try to google or to look at [Git Submodules doc](https://git-scm.com/book/it/v2/Git-Tools-Submodules).

Please tell me if you understood or if you have any other question, otherwise have a good weekend and a good day ^^

**Comment by ScrappyCocco** [comment]
Closed for no reply
