### ISSUE TITLE
Use premake to make the engine development compatible across Windows and Linux

### ISSUE THREAD

**Issue by rhythm1705** [ScrappyCocco/ScrapEngine#42]
Premake can allow you to create setup for VS,  CMake and more easily.

**Comment by ScrappyCocco** [comment]
Hello and thanks for the feedback!

I had in mind to add Cmake to allow the engine to run on linux. Unfortunatelly, I ended up adding stuff to it more than thinking about porting it.

It's not only about the build system anyway, to port this engine on linux some window/surface and i/o methods need to be changed.

Since I'm very busy with my internship and my last exams, I will not do it soon, sorry.

**Comment by rhythm1705** [comment]
No problem! I am also trying to learn vulkan + computer graphics and working on my own game engine as well by using yours as an inspiration. Good luck with your exams and internship!

**Comment by ScrappyCocco** [comment]
Thanks and good luck to you too. 

Feel free to open an issue if you have any question
